apiVersion: v1
kind: Secret
metadata:
  name: <%= ssh_secret_name %>
  namespace: <%= namespace %>
  annotations:
    tekton.dev/git-0: bitbucketprod.toll.no
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: <%= base64encoded_private_key %>
