apiVersion: v1
kind: Secret
metadata:
  name: toffen-pipeline-trigger-secret
  namespace: toffen
type: Opaque
stringData:
  secretToken: "1234567"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: toffen-pipeline-trigger
  namespace: toffen
secrets:
  - name: toffen-pipeline-trigger-secret